# api-gateway/src/main/resources/application.yml

server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      
      routes:
        - id: account-service-routes
          uri: http://account-service:8081
          predicates:
            - Path=/auth/**, /users/**, /accounts/**, /audit/**
        
        - id: wallet-service-routes
          uri: http://wallet-service:8082
          predicates:
            - Path=/wallets/**, /transactions/**

        - id: order-service-routes
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**


# JWT Configuration (inchangé)
jwt:
  secret: ${JWT_SECRET:mySecretKeyForBrokerXPlatform2025ThisIsVerySecretAndLongEnough}

# Management/Actuator (inchangé)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always

# Logging (inchangé)
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.brokerx: INFO