server:
  port: 8083

spring:
  application:
    name: order-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/brokerx}
    username: ${SPRING_DATASOURCE_USERNAME:brokerx_user}
    password: ${SPRING_DATASOURCE_PASSWORD:brokerx_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForBrokerXPlatform2025ThisIsVerySecretAndLongEnough}
  expiration: 86400000

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.brokerx: INFO
    org.springframework.security: DEBUG