name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to VM
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy Microservices
        run: |
          docker-compose -f docker-compose-microservices.yml down || true
          docker-compose -f docker-compose-microservices.yml up -d --build
          
      - name: Health Check
        run: |
          sleep 45
          curl -f http://localhost:8080/health || echo "Health check warning"
          
      - name: Show logs
        if: always()
        run: docker-compose -f docker-compose-microservices.yml logs --tail=50